version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # timescaledb:
  #   image: timescale/timescaledb:latest-pg16
  #   container_name: timescaledb
  #   restart: always
  #   environment:
  #     POSTGRES_USER: atkins
  #     POSTGRES_PASSWORD: hackafuture
  #     POSTGRES_DB: timeseries
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - timescale_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: atkins
      MYSQL_PASSWORD: hackafuture
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
